services:
  kafka:
    image: confluentinc/cp-kafka:7.8.3
    container_name: kafka
    ports:
      - "9092:9092"

    environment:
      KAFKA_KRAFT_MODE: 'true'

      CLUSTER_ID: '1L6g7nGhU-eAKfL--X25wo'
      KAFKA_NODE_ID: 1

      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs

    volumes:
      - kafka_kraft:/var/lib/kafka/data
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=my-cluster
      - node.name=elasticsearch-01
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=false"
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data
    
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql

  init_db:
    build: ./db
    container_name: init_db
    environment:
      DB_URL: mysql+pymysql://user:password@mysql/mydb
    depends_on:
      - mysql
    
  intel_service:
    build: ./intel_service
    container_name: intel_service
    environment:
      DB_URL: mysql+pymysql://user:password@mysql/mydb
      KAFKA_URI : kafka:9092
    depends_on:
      - mysql
      - kafka
      - init_db
  
  attack_service:
    build: ./attack_service
    container_name: attack_service
    environment:
      DB_URL: mysql+pymysql://user:password@mysql/mydb
      KAFKA_URI : kafka:9092
    depends_on:
      - mysql
      - kafka
      - init_db

  damage_service:
    build: ./damage_service
    container_name: damage_service
    environment:
      DB_URL: mysql+pymysql://user:password@mysql/mydb
      KAFKA_URI : kafka:9092
    depends_on:
      - mysql
      - kafka
      - init_db

volumes:
  kafka_kraft:
  esdata:
  db_data: